version: '3'
services: 
  gotest: 
    build:  
     context: ./gotest
     args:
      - workdir=/go/src/gotest
    ports:
     - '8181:8181'   
    volumes:
      - './gotest/gotest:/go/src/gotest'
    # command: bee run
    links:
      - mysql
    # tty: true 
  webcron:
    build:
      context: ./webcron
      args:
        - workdir=/go/src/webcron
    ports:
      - '8000:8000'     
    volumes:
      - './webcron/webcron:/go/src/webcron'  
    command: bee run
    links:
      - mysql  
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_ROOT_PASSWORD=123456 #mysql root password
    ports:
      - '3306:3306'    #mysql port
    volumes:
      - './mysql/conf:/etc/mysql/conf.d' #mysql custom conf files
      - './mysql/datadir:/var/lib/mysql' #mysql data files
    tty: true   