version: '3'
services: 
  go: 
    build:  
     context: ./go
     args:
      - workdir=/go/src/gotest
    ports:
     - '8181:8181'   
    volumes:
      - './go/gotest:/go/src/gotest'
    command: bee run
    tty: true  
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_ROOT_PASSWORD=123456 #mysql root password
    ports:
      - '3306:3306'    #mysql port
    volumes:
      - './mysql/conf:/etc/mysql/conf.d' #mysql custom conf files
      - './mysql/datadir:/var/lib/mysql' #mysql data files
    tty: true   